/**
 * `recall(text)` controller.
 *
 * Orchestrates the narrow MVP pipeline:
 *
 *   1. Defensive shape check on the query string (handled at the
 *      tool boundary, not repeated here).
 *   2. Safety pre-check on the query. A query that contains a
 *      secret-shaped fragment is rejected — we do not log it, we
 *      do not forward it to the provider, and we do not use it to
 *      search stored memories. The public response is a rejection
 *      message that does not echo the query.
 *   3. Read the safe stored memory summaries from local storage.
 *   4. Lexically rank the stored summaries against the query.
 *      If none passes the relevance threshold, return
 *      `no_memory` and DO NOT call the provider.
 *   5. If relevant memories exist, send the small set of top
 *      summaries to the recall-synthesis provider and ask it to
 *      answer the query from memory only.
 *   6. Validate the synthesized answer: non-empty, no obvious
 *      secret-shaped fragments, no obvious raw-dump shape. If
 *      validation fails, return `provider_error` (we never expose
 *      an unsafe or fabricated public answer).
 *   7. Return the synthesized answer to the tool layer.
 *
 * Design notes:
 *   - The controller never calls the provider with raw user text.
 *     The query is passed to the provider only as a search
 *     instruction inside the synthesis prompt, and the synthesis
 *     prompt itself never echoes the query back as the answer
 *     (it asks the model to answer FROM memories only).
 *   - The controller never persists the recall query, the
 *     provider's raw response, or the synthesized answer. The
 *     recall MVP is read-only against the memories table.
 *   - The controller never logs the raw query text. It logs a
 *     short, redacted reason on the pre-check, and a fixed-shape
 *     debug line on the storage read / provider call, with no
 *     secret fragments.
 */

import { classifyInput } from "../safety/precheck.js";
import type { Clarification } from "../tools/remember-structured-content.js";
import {
  listActiveMemorySummaries,
  listActiveMemoryRelationshipBlocks,
  getEmbeddingsForMemories,
  type SafeMemorySummary,
  type StorageHandle,
} from "../storage/storage.js";
import {
  rankLexical,
  scoreCandidateDetailed,
  DEFAULT_RELEVANCE_THRESHOLD,
  DEFAULT_TOP_K,
  type LexicalScoredCandidate,
} from "../retrieval/lexical.js";
import {
  demoteSupersededMemories,
  type ScoredCandidateWithRelationship,
} from "../retrieval/superseded-demotion.js";
import {
  detectAmbiguity,
  type AmbiguitySignal,
  type SafeMemorySummaryWithRelationship,
} from "../retrieval/ambiguity.js";
import {
  detectResolvedHistory,
  type ResolvedHistorySignal,
} from "../retrieval/resolved-history.js";
import {
  synthesizeRecallWithFallback,
  type RecallSynthesisOptions,
  type RecallSynthesisResult,
  type RecallMemoryInput,
} from "../providers/recall-synthesis.js";
import { redactSummary } from "../safety/precheck.js";
import { logger } from "../logging/logger.js";
import {
  RECALL_ACTIVE_MEMORY_READ_KIND,
  RECALL_LEXICAL_RANKING_KIND,
  RECALL_SELECTED_CANDIDATES_KIND,
  RECALL_SUPERSEDED_DEMOTION_KIND,
} from "../trace/trace-tool-boundary.js";
import type { SemanticEmbedder } from "../retrieval/semantic/embedder.js";
import {
  createSemanticEmbedder,
} from "../retrieval/semantic/embedder.js";
import {
  fuseLexicalAndSemantic,
  scoreSemanticCandidates,
} from "../retrieval/semantic/score.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Public outcome of the recall controller. */
export type RecallOutcome =
  | {
      status: "answered";
      answer: string;
      /** Memory ids the answer was synthesized from (in rank order). */
      sourceIds: number[];
      /**
       * Internal-only conservative ambiguity signal from the
       * recall-side detector (Phase C).
       *
       * This field is observable to tests and any future
       * structured-content transport, but it is NEVER
       * serialized into the public MCP `text` content block.
       * The `src/tools/recall.ts` projection explicitly drops
       * it; the public message / answer is unchanged.
       *
       * Public-message behaviour on the `ambiguous` verdict
       * is described in spec §5.4 and is implemented in
       * Phase D. The note is generated by
       * `formatAmbiguityNote` in `src/retrieval/ambiguity.ts`.
       */
      internalAmbiguity?: AmbiguitySignal;
      /**
       * Internal-only conservative resolved-history signal
       * from the recall-side detector (Phase H + Phase J).
       *
       * The Architect recommended a **parallel** internal
       * field rather than merging the new variant into the
       * existing `AmbiguitySignal` union: the two detectors
       * have different rule sets (marker-based vs
       * pointer-based), different confidence floors, and
       * different public notes. A merged union would force
       * every consumer to discriminate on `kind` (and
       * treat `resolved-history` as a third variant),
       * with no readability win. A parallel field keeps
       * the Phase D and Phase J code paths structurally
       * independent: the tool layer can compose the two
       * notes via two short, independent helper calls,
       * and the public projection remains a simple
       * `if (note.length > 0) message = note + answer`.
       *
       * This field is observable to tests and any future
       * structured-content transport, but it is NEVER
       * serialized into the public MCP `text` content
       * block. The `src/tools/recall.ts` projection
       * explicitly drops it; the public message / answer
       * is unchanged unless the note (added in Phase J)
       * is prefixed. The note is generated by
       * `formatResolvedHistoryNote` in
       * `src/retrieval/resolved-history.ts`.
       */
      internalResolvedHistory?: ResolvedHistorySignal;
    }
  | { status: "no_memory"; clarification?: Clarification }
  | {
      /**
       * Refusal-with-thin-match reroute. The synthesis LLM
       * declined to answer (the `isProviderRefusal` detector
       * fired) but the lexical ranker did surface at least
       * one stored summary above the relevance threshold.
       * The controller surfaces the top-3 curator-voice
       * summaries and a coverage block so the caller has
       * something to inspect instead of a misleading
       * `no_memory` (which says "nothing relevant was
       * found") or a fabricated `answered` (which would
       * leak the refusal prose on the wire).
       *
       * The `summaries` are plain strings (no memory-id
       * reference), capped at 3 by the controller. The
       * `coverage.topScore` is the raw lexical score of
       * the top-ranked candidate (a confidence proxy for
       * the ranker); `coverage.supportingCount` is the
       * count of summaries that passed the ranker
       * threshold, NOT capped by the top-K=3 slice. A
       * future curator summary that contains an id
       * reference would have the same write-path source
       * as the existing `answered.answer` field, so the
       * no-IDs rule is enforced at the schema level (the
       * `summaries` field is structurally a list of
       * strings with no id-bearing child objects), not at
       * the content level.
       */
      status: "weak_match";
      summaries: string[];
      coverage: { topScore: number; supportingCount: number };
      clarification?: Clarification;
    }
  | { status: "rejected"; reason: string; safetyClass: string; clarification?: Clarification }
  | { status: "provider_error"; reason: string };

/** Controller options. Most fields have safe defaults. */
export interface RecallControllerOptions {
  /** Minimum lexical score to keep a candidate. Default 0.2. */
  relevanceThreshold?: number;
  /** Max number of top summaries sent to the provider. Default 5. */
  topK?: number;
  /** Enable semantic retrieval hybrid. Default false (lexical only). */
  semanticEnabled?: boolean;
  /**
   * Optional injected semantic embedder. When provided, the semantic
   * path runs regardless of `semanticEnabled` (semanticEnabled is
   * still respected for whether hybrid fusion occurs, but the embedder
   * itself is used directly). When omitted, the controller creates
   * an embedder internally only when `semanticEnabled` is true.
   *
   * Tests should pass this directly to exercise the semantic path
   * without relying on the tool layer's embedder factory.
   */
  semanticEmbedder?: SemanticEmbedder;
  /** Optional fetch override for tests. */
  providerFetchImpl?: typeof fetch;
  /** Optional API key override for the primary provider. */
  providerPrimaryApiKey?: string;
  /** Optional API key override for the fallback provider. */
  providerFallbackApiKey?: string;
  /** Optional base URL override for the primary provider. */
  providerPrimaryBaseUrl?: string;
  /** Optional base URL override for the fallback provider. */
  providerFallbackBaseUrl?: string;
  /** Optional model id override for the primary provider. */
  providerPrimaryModel?: string;
  /** Optional model id override for the fallback provider. */
  providerFallbackModel?: string;
  /** Max number of stored summaries scanned. Default 200. */
  storageLimit?: number;
  /**
   * Optional Phase 3A trace plumbing. The tool-boundary handler
   * (and any direct caller that has its own trace run) passes a
   * small context object so the controller can emit
   * `recall.active-memory-read`, `recall.lexical-ranking`, and
   * `recall.selected-candidates` stage events on the SAME trace
   * run that the public tool boundary opens.
   *
   * The context is optional. When omitted (the default), the
   * controller emits no stage events; existing callers are
   * unaffected. The `recordStage` callback is expected to be
   * non-throwing — the controller does not wrap it in a
   * try/catch because the canonical implementation is the
   * existing `ToolBoundaryTracer.recordStage`, which already
   * short-circuits on disabled / closed writers. The controller
   * also short-circuits when `runId` is null, so an already-
   * disabled tracer never sees a call.
   *
   * NOT in this phase:
   *   - Provider I/O capture (request / response bodies).
   *   - Remember-side stage events.
   *   - A CLI / export / purge surface.
   */
  trace?: RecallTraceContext;
}

/**
 * Trace plumbing passed in by the caller. The controller uses
 * this to emit per-stage events on the same run as the public
 * tool-boundary events.
 *
 * `runId` is `null` when the writer is closed or tracing is
 * disabled; the controller checks this before every emission so
 * the disabled path is a true no-op (no allocation, no string
 * formatting, no callback invocation).
 *
 * `recordStage` is the only emission method the controller
 * uses. The kind tag is owned by the controller (the
 * `RECALL_*_KIND` constants in the trace module); the payload
 * is the controller's, the redaction is the writer's.
 */
export interface RecallTraceContext {
  /**
   * Same run id as the public tool-boundary tracer, or `null`
   * when tracing is disabled / writer is closed. The controller
   * only emits when this is non-null.
   */
  runId: number | null;
  /**
   * Non-throwing stage-event recorder. Routes through the
   * existing trace writer; payloads are redacted by the
   * writer's `redactPayload` pass before being persisted.
   */
  recordStage: (kind: string, payload: unknown) => void;
}

// ---------------------------------------------------------------------------
// Defaults
// ---------------------------------------------------------------------------
//
// No length cap on the synthesized answer. The synthesis prompt and
// the disciplined model choice (gpt-oss-120b as primary) control
// length on the input side. The hard 800-character cap that lived
// here was a placeholder; it has been removed entirely so natural-
// length answers go to the wire unmodified.

// ---------------------------------------------------------------------------
// Controller
// ---------------------------------------------------------------------------

/**
 * Run the narrow MVP `recall` pipeline.
 *
 * Public MCP API is unchanged. This function is consumed by
 * `src/tools/recall.ts`. The controller never throws on expected
 * failure paths; it returns a discriminated union.
 *
 * Important behavior:
 *   - If no stored memory passes the relevance threshold, the
 *     provider is NOT called. We return `no_memory`.
 *   - If the query contains a secret-shaped fragment, the provider
 *     is NOT called and the query is NOT used for retrieval. We
 *     return `rejected` (the public message does not echo the
 *     query). The query text is not logged.
 *   - If the provider fails, we return `provider_error` with a
 *     short, redacted reason. We never fabricate an answer.
 *   - If the provider's answer is empty or contains a
 *     secret-shaped fragment or a raw-dump shape, we return
 *     `provider_error`. We never expose an unsafe public answer.
 */
export async function runRecallController(
  storage: StorageHandle,
  query: string,
  options: RecallControllerOptions = {},
): Promise<RecallOutcome> {
  const threshold = options.relevanceThreshold ?? DEFAULT_RELEVANCE_THRESHOLD;
  const topK = options.topK ?? DEFAULT_TOP_K;
  const storageLimit = options.storageLimit ?? 200;

  // -- 1. Safety pre-check on the query -------------------------------
  //
  // Decision (safer temporary default): reject queries that contain
  // obvious secrets. This matches the remember controller's policy
  // on inputs: secret-shaped fragments must not be forwarded to a
  // provider or used to search storage. The MCP schema already
  // rejects empty queries at the tool boundary; we add this layer
  // as defense in depth. The public message does not echo the
  // query.
  const safety = classifyInput(query);
  logger.debug(
    `recall: pre-check class=${safety.class} reason=${safety.reason}`,
  );
  if (safety.class === "secret") {
    return {
      status: "rejected",
      reason:
        "query contains a secret-shaped fragment; refusing to search or forward it",
      safetyClass: "secret",
    };
  }
  if (safety.class === "mixed-safe-sensitive") {
    return {
      status: "rejected",
      reason:
        "query mixes safe and sensitive fragments; please rephrase the query to remove the sensitive part",
      safetyClass: "mixed-safe-sensitive",
    };
  }
  // Note: we intentionally do NOT route prompt-injection /
  // unsafe-preference / raw-dump / self-conflict / vague-junk
  // inputs to a hard reject here. The recall path is read-only
  // and read-only queries are less dangerous than remember
  // inputs (no persistence, no per-record mutation). A vague
  // query simply yields no matches. The downstream lexical
  // ranker handles them naturally.

  // -- 2. Read safe stored summaries ----------------------------------
  const summaries = listActiveMemorySummaries(storage, {
    limit: storageLimit,
  });
  logger.debug(
    `recall: read ${summaries.length} safe summary(ies) from storage`,
  );
  // Parallel lookup of stored `relationship` blocks
  // (Phase C). The controller uses this only for the
  // internal `internalAmbiguity` field on the answered
  // outcome. The public recall pipeline does not surface
  // these blocks in any other way. The two read functions
  // share the same `state = 'active'` filter and the same
  // ascending `id` order, so the controller can project
  // the block onto a candidate by id lookup below.
  const relationshipBlocks = listActiveMemoryRelationshipBlocks(storage, {
    limit: storageLimit,
  });
  const blockById = new Map<number, (typeof relationshipBlocks)[number]["block"]>();
  for (const r of relationshipBlocks) {
    blockById.set(r.id, r.block);
  }

  // -- Phase 3A trace: active memory read --------------------------------
  emitActiveMemoryReadStage(options.trace, {
    readCount: summaries.length,
    storageLimit,
  });

  // -- 3. Lexical ranking ---------------------------------------------
  // Run lexical ranking on ALL summaries (not limited by topK) to build
  // the candidate pool for semantic fusion. Using storageLimit as the
  // lexical topK limit gives semantic the broadest possible pool to
  // recover paraphrase hits that lexical would miss.
  const lexicalTopK = options.semanticEnabled ? storageLimit : topK;
  const ranked: LexicalScoredCandidate[] = rankLexical(
    query,
    summaries.map((s: SafeMemorySummary) => ({
      id: s.id,
      text: s.memoryContent,
      tags: s.tags,
    })),
    { threshold, topK: lexicalTopK },
  );
  // Build the id->summary map once; used by both the trace
  // event and the topSummaries construction below.
  const summaryById = new Map<number, SafeMemorySummary>(
    summaries.map((s) => [s.id, s]),
  );
  // -- Phase 3A trace: lexical ranking (before demotion) ----------------
  // The trace records the raw lexical ranking; the demotion
  // is a pure post-rank step that only reorders candidates
  // when superseded relationships exist in the candidate set.
  emitLexicalRankingStage(options.trace, {
    query,
    threshold,
    topK: lexicalTopK,
    ranked,
    summariesById: summaryById,
  });

  // -- 3b. Semantic retrieval and hybrid fusion -------------------------
  // When semanticEnabled is true OR an embedder is explicitly injected,
  // run semantic scoring on the broadest possible pool (all summaries
  // with embeddings) and fuse with lexical. This allows semantic to
  // recover paraphrase hits that lexical topK would not include.
  //
  // Behavior:
  //   - semanticEmbedder injected (tests): use it directly, no internal creation.
  //   - semanticEnabled only: controller creates embedder internally (tool-layer
  //     design — controller does NOT create heavy defaults).
  //   - Neither: semantic path is skipped (lexical-only).
  let finalRanked = ranked;
  const shouldRunSemantic = options.semanticEmbedder != null || options.semanticEnabled;
  if (shouldRunSemantic) {
    try {
      // Use injected embedder if provided; otherwise create one internally.
      const embedder = options.semanticEmbedder ?? await createSemanticEmbedder({ enabled: true });
      // Only proceed if embedder is ready (not error status)
      if (embedder.metadata.status === "ready") {
        // Get embeddings for ALL summaries that have them, not just topK.
        // This is the key: semantic should see the full active pool.
        const allMemoryIds = summaries.map((s) => s.id);
        const embeddings = getEmbeddingsForMemories(storage, allMemoryIds);
        if (embeddings.size > 0) {
          // Embed the query once.
          const queryVec = await embedder.embed(query, "query");
          // Score ALL candidates that have embeddings.
          const semCandidates = Array.from(embeddings.values()).map((e) => ({
            id: e.memoryId,
            vec: e.vec,
          }));
          const semRanked = scoreSemanticCandidates(queryVec, semCandidates);
          // Fuse semantic with lexical. Use weights that favor semantic
          // slightly for paraphrase recovery while preserving lexical signal.
          const fused = fuseLexicalAndSemantic(
            ranked,
            semRanked,
            { lexical: 1, semantic: 1 },
            60, // RRF k constant
            storageLimit, // Consider top storageLimit candidates in fusion
          );
          finalRanked = fused;
          logger.debug(
            `recall: semantic fused ${ranked.length} lexical + ${semRanked.length} semantic -> ${fused.length} final`,
          );
        } else {
          logger.debug("recall: semantic enabled but no embeddings stored");
        }
      } else {
        logger.debug(
          `recall: semantic embedder not ready (status: ${embedder.metadata.status})`,
        );
      }
    } catch (err) {
      // Non-fatal: fall back to lexical-only if semantic fails.
      logger.debug(
        `recall: semantic retrieval failed: ${(err as Error).message}; falling back to lexical`,
      );
    }
  }

  // Early exit check AFTER semantic fusion.
  // When semantic is enabled, we defer the check until after fusion
  // so semantic can recover memories that lexical threshold filtered out.
  if (finalRanked.length === 0) {
    logger.debug("recall: no relevant memory; skipping provider call");
    // Add clarification for obviously vague/underspecified queries.
    if (isVagueQuery(query)) {
      return {
        status: "no_memory",
        clarification: {
          reason: "query is vague or underspecified; no memories matched",
          question:
            "Could you be more specific about what you're looking for? For example, what topic or project was this about?",
        },
      };
    }
    return { status: "no_memory" };
  }

  // -- 3c. Superseded-memory demotion -----------------------------------
  // When both a superseding candidate (A) and its superseded target (B)
  // are present in the ranked set, demote B so A ranks higher.
  // Missing references are silently ignored. The demotion is a pure
  // reordering step; no I/O, no state change.
  const scoredWithRelationships: ScoredCandidateWithRelationship[] = finalRanked.map(
    (r) => {
      const block = blockById.get(r.id);
      return block === undefined
        ? { id: r.id, score: r.score }
        : {
            id: r.id,
            score: r.score,
            relationship: {
              supersedes: block.supersedes,
              supersededBy: block.supersededBy,
            },
          };
    },
  );
  const demotedRanked = demoteSupersededMemories(scoredWithRelationships);

  // -- Phase 3A trace: superseded demotion --------------------------------
  // Compute the stale-id set and superseding-id map from the scored
  // candidates so the trace event can summarize what was demoted and why.
  // This mirrors the logic in `demoteSupersededMemories` but surfaces
  // the intermediate data for tracing.
  const candidateIds = new Set<number>(scoredWithRelationships.map((c) => c.id));
  const demotedIds = new Set<number>();
  const supersededByMap = new Map<number, number>(); // staleId -> supersedingId
  for (const c of scoredWithRelationships) {
    const rel = c.relationship;
    if (!rel) continue;
    if (rel.supersedes) {
      for (const otherId of rel.supersedes) {
        if (typeof otherId !== "number" || !Number.isFinite(otherId)) continue;
        if (candidateIds.has(otherId)) {
          demotedIds.add(otherId);
          // reason for otherId is "supersededBy"; supersedingId is c.id
          supersededByMap.set(otherId, c.id);
        }
      }
    }
    if (rel.supersededBy) {
      for (const otherId of rel.supersededBy) {
        if (typeof otherId !== "number" || !Number.isFinite(otherId)) continue;
        if (candidateIds.has(otherId)) {
          demotedIds.add(c.id);
          // reason for c.id is "supersededBy"; supersedingId is otherId
          supersededByMap.set(c.id, otherId);
        }
      }
    }
  }
  emitSupersededDemotionStage(options.trace, {
    before: ranked.map((r) => ({ id: r.id, score: r.score })),
    after: demotedRanked.map((r) => ({ id: r.id, score: r.score })),
    demotedIds,
    supersededByMap,
  });

  // Re-attach summaries in the order returned by the demoted ranker.
  // demotedRanked carries the score-sorted order (post-demotion).
  // We use a single O(N) map lookup so this stays linear even if
  // the store grows. The relationship block (Phase C) is
  // attached as an optional extension; rows without a stored
  // block carry `relationship: undefined` and the detector
  // treats them as having no stored data (it can still fire
  // on the lexical / asymmetric-negation path).
  const topSummaries: SafeMemorySummaryWithRelationship[] = [];
  for (const r of demotedRanked) {
    const s = summaryById.get(r.id);
    if (!s) continue;
    const block = blockById.get(r.id);
    topSummaries.push(
      block === undefined
        ? { ...s }
        : { ...s, relationship: { ...block } },
    );
  }
  // Sanity: every ranked id must have a summary. If this ever
  // fails, it means a memory was deleted between the read and
  // the rank — fall back to no_memory rather than fabricating.
  if (topSummaries.length !== demotedRanked.length) {
    logger.debug(
      "recall: ranked-id missing summary (storage raced); returning no_memory",
    );
    return { status: "no_memory" };
  }

  // -- Phase 3A trace: selected candidates -----------------------------
  emitSelectedCandidatesStage(options.trace, topSummaries);

  // -- 4. Provider synthesis -----------------------------------------
  const adapterOptions: RecallSynthesisOptions = {};
  if (options.providerFetchImpl !== undefined) {
    adapterOptions.fetchImpl = options.providerFetchImpl;
  }
  if (options.providerPrimaryApiKey !== undefined) {
    adapterOptions.primaryApiKey = options.providerPrimaryApiKey;
  }
  if (options.providerFallbackApiKey !== undefined) {
    adapterOptions.fallbackApiKey = options.providerFallbackApiKey;
  }
  if (options.providerPrimaryBaseUrl !== undefined) {
    adapterOptions.primaryBaseUrl = options.providerPrimaryBaseUrl;
  }
  if (options.providerFallbackBaseUrl !== undefined) {
    adapterOptions.fallbackBaseUrl = options.providerFallbackBaseUrl;
  }
  if (options.providerPrimaryModel !== undefined) {
    adapterOptions.primaryModel = options.providerPrimaryModel;
  }
  if (options.providerFallbackModel !== undefined) {
    adapterOptions.fallbackModel = options.providerFallbackModel;
  }

  const memories: RecallMemoryInput[] = topSummaries.map((s) => ({
    id: s.id,
    memoryContent: s.memoryContent,
    kind: s.kind,
    tags: s.tags,
  }));
  const result: RecallSynthesisResult = await synthesizeRecallWithFallback(
    query,
    memories,
    adapterOptions,
  );

  if (!result.ok) {
    logger.debug(`recall: provider error: ${result.kind} (${result.message})`);
    return {
      status: "provider_error",
      reason: result.message,
    };
  }

  // -- 5. Validate the synthesized answer ----------------------------
  const validation = validateAnswer(result.answer);
  if (!validation.ok) {
    if (validation.reason === "refusal_detected") {
      // Refusal-with-thin-match reroute. The synthesis LLM
      // declined to answer (the `isProviderRefusal` detector
      // fired). If the lexical ranker found at least one
      // stored summary above the relevance threshold, the
      // "no relevant memory was found" framing of `no_memory`
      // would be misleading — the ranker DID find something,
      // it just could not be synthesized into a confident
      // answer. In that case we surface a `weak_match`
      // outcome that exposes the top-3 curator-voice
      // summaries and a coverage block, so the caller can
      // inspect the closest stored memories instead of
      // receiving a blank "No relevant memory found.".
      //
      // If the ranker found nothing (`topSummaries.length
      // === 0`), the refusal is genuinely "no memory to
      // reason about" and we fall back to `no_memory` as
      // before. Note: in practice `topSummaries` is
      // guaranteed non-empty here — the controller
      // short-circuits with `no_memory` at the rank-empty
      // branch above — but the explicit check keeps the
      // reroute site defensive and matches the brief's
      // trigger condition (`topSummaries.length > 0`).
      if (topSummaries.length > 0) {
        logger.debug(
          "recall: provider answer was a refusal; rerouting to weak_match",
        );
        const topScore = finalRanked[0]!.score;
        const supportingCount = finalRanked.length;
        const out: RecallOutcome = {
          status: "weak_match",
          summaries: topSummaries.slice(0, 3).map((s) => s.memoryContent),
          coverage: {
            topScore,
            supportingCount,
          },
        };
        // Add clarification when coverage suggests competing/conflicting
        // candidates or very weak match quality.
        if (suggestsCompetingCandidates(topScore, supportingCount)) {
          out.clarification = {
            reason: "query matched multiple memories with low confidence; synthesis LLM declined to answer",
            question:
              "I found several related memories but wasn't confident synthesizing an answer. Could you rephrase your question or be more specific about what you're looking for?",
          };
        }
        return out;
      }
      logger.debug(
        "recall: provider answer was a refusal; rerouting to no_memory",
      );
      // Also check if the query is vague for the no_memory fallback.
      if (isVagueQuery(query)) {
        return {
          status: "no_memory",
          clarification: {
            reason: "query is vague or underspecified; no memories matched",
            question:
              "Could you be more specific about what you're looking for? For example, what topic or project was this about?",
          },
        };
      }
      return { status: "no_memory" };
    }
    logger.debug(
      `recall: provider answer rejected: ${validation.reason}`,
    );
    return {
      status: "provider_error",
      reason: validation.reason,
    };
  }
  // Use the redacted form so any secret-shaped fragment the
  // model produced (defense in depth) is removed before we hand
  // the text to the tool layer. The validator above already
  // rejected answers that are entirely or mostly redacted.
  const safeAnswer = validation.answer;

  // -- 6. Internal ambiguity detection (Phase C) ----------------------
  // Conservative offline detector. The signal is attached
  // to the answered outcome as an internal-only field.
  // `src/tools/recall.ts` is responsible for dropping it
  // from the public projection. The public message / answer
  // remain byte-equal to pre-Phase-C for every status
  // branch. The detector does NOT short-circuit the
  // pipeline; the provider call above always runs.
  const internalAmbiguity: AmbiguitySignal = detectAmbiguity({
    topCandidates: topSummaries,
    answer: safeAnswer,
  });

  // -- 7. Internal resolved-history detection (Phase H + J) -----------
  // Conservative offline detector that recognises an
  // **explicit** resolution marker pair (`previous` /
  // `old` / `superseded` / `no longer` on the previous
  // side; `current` / `replaced` on the current side),
  // with a referential-pointer variant (Pattern B in spec
  // §5.2). The detector is structurally parallel to the
  // Phase C ambiguity detector above but uses a different
  // rule set; the two signals live on separate internal
  // fields on the answered outcome (see the
  // `internalResolvedHistory` field on `RecallOutcome`).
  // The detector does NOT short-circuit the pipeline.
  // `src/tools/recall.ts` is responsible for the public
  // projection: it composes `formatAmbiguityNote` and
  // `formatResolvedHistoryNote` into a single prefix on
  // the public `message` (the ambiguity note takes
  // precedence per spec §4.2 / §4.3: a stored conflict
  // pointer wins, and the detector stays silent on
  // resolved-history when the Phase D detector would
  // fire). When both notes are empty, the public
  // `message` is byte-equal to the synthesized answer
  // (pre-Phase-J invariant, preserved for the no-detector
  // case).
  const internalResolvedHistory: ResolvedHistorySignal = detectResolvedHistory({
    topCandidates: topSummaries,
    answer: safeAnswer,
  });

  return {
    status: "answered",
    answer: safeAnswer,
    sourceIds: topSummaries.map((s) => s.id),
    internalAmbiguity,
    internalResolvedHistory,
  };
}

// ---------------------------------------------------------------------------
// Internal answer validation
// ---------------------------------------------------------------------------

interface AnswerOk {
  ok: true;
  /** Validated + redacted answer text. */
  answer: string;
}

interface AnswerFail {
  ok: false;
  reason: string;
}

/**
 * Strip memory-id references from the answer text before projection.
 *
 * The no-IDs-in-public-text invariant forbids memory-id fields on
 * the wire (the no-IDs rule is field-level, not content-level — see
 * `src/tools/recall-structured-content.ts` and `HANDOVER.md`).
 * However, the synthesis LLM may echo the id-bearing format
 * `- #N kind: summary` it sees in its prompt into its synthesized
 * answer, producing prose like "Memory #20 documents the
 * lexical-only production recall boundary". This strip pass removes
 * such references from the answer text before it reaches the
 * public projection so the public `text` block stays free of
 * memory-id mentions.
 *
 * Patterns stripped (case-insensitive):
 *   - `Memory #N`, `Memories #N`
 *   - `entry #N`, `record #N`, `note #N`, `summary #N`
 *   - bare `#N` that follows a word boundary, e.g. "(see #37)",
 *     "as in #37", "PR is #42"
 *
 * The pass is conservative: it does NOT strip `#N` inside URLs
 * (which contain `://` and `/`), inside hex colors, or inside
 * quoted technical content. Only the patterns listed above are
 * touched.
 *
 * Each match is replaced with the literal placeholder `[memory]`,
 * which preserves sentence structure and makes the strip auditable.
 * Adjacent placeholders are collapsed into a single one so the
 * public text is not visibly noisy.
 */
function stripMemoryIdReferences(text: string): string {
  if (typeof text !== "string" || text.length === 0) return text;
  let out = text;
  // Pattern 1: "Memory #N" or "Memories #N" (case-insensitive).
  out = out.replace(/\b(memory|memories)\s+#\d+\b/gi, "[memory]");
  // Pattern 2: "entry #N", "record #N", "note #N", "summary #N"
  // (case-insensitive). These are the same memory-record nouns
  // used by `isProviderRefusal`'s noun alternation.
  out = out.replace(
    /\b(entry|record|note|summary)\s+#\d+\b/gi,
    "[memory]",
  );
  // Pattern 3: bare `#N` that follows a word boundary. We require
  // the character immediately before `#` to be whitespace,
  // `(`, `,`, or the start of the string. This skips `#N` that
  // appears inside URLs (where the preceding characters are
  // `://` or `/`), inside hex colors (`#ffffff`), and inside
  // quoted technical content. We also cap the digit run at 1-6
  // characters so a long hash-shaped fragment is never matched.
  out = out.replace(
    /(^|[\s(,])(#\d{1,6})\b/g,
    (_match, prefix: string) => `${prefix}[memory]`,
  );
  // Collapse runs of adjacent `[memory]` placeholders to a single
  // one, so a multi-reference sentence does not become visually
  // noisy in the public text.
  out = out.replace(/(\[memory\]\s*){2,}/g, "[memory]");
  // Tidy up a placeholder that would otherwise leave a dangling
  // space before a punctuation mark or a sentence break.
  out = out.replace(/\[memory\]\s+([,.;:!?])/g, "[memory]$1");
  return out;
}

/**
 * Strip provider-side reasoning blocks from the answer text so the
 * public output is the visible answer only.
 *
 * Removes, in order:
 *   1. `<think>...</think>` blocks — multiline, case-insensitive.
 *   2. `<thinking>...</thinking>` blocks — multiline, case-insensitive.
 *   3. A single leading `Reasoning:` or `Thought:` block — bounded
 *      to the first 2000 chars and only stripped when followed by
 *      a blank line and visible answer text. This is intentionally
 *      conservative: it must not eat the real answer if the model
 *      just happened to use the word "Reasoning" in normal prose.
 *
 * The function never throws and never expands the input. If nothing
 * matches, the input is returned (trimmed) unchanged.
 */
function stripReasoningBlocks(answer: string): string {
  if (typeof answer !== "string" || answer.length === 0) return answer;
  let text = answer;
  // 1) and 2): HTML-style reasoning tags, multiline, case-insensitive.
  // The `s` flag (dotAll) lets `.` match newlines.
  text = text.replace(
    /<\s*think(?:ing)?\s*>[\s\S]*?<\s*\/\s*think(?:ing)?\s*>/gi,
    "",
  );
  // 3) Bounded leading "Reasoning:" / "Thought:" blocks. We only
  // strip when (a) the block is at the start of the text (after
  // trimming), (b) the label is exactly "Reasoning:" or "Thought:"
  // (not a normal sentence that happens to start with the word),
  // and (c) the block is followed by a blank line before the
  // visible answer. This avoids eating legitimate prose.
  const leadingLabelMatch = text.match(
    /^\s*(?:Reasoning|Thought)\s*:\s*([\s\S]{0,2000}?)(?:\n\s*\n|\n\s*$)/i,
  );
  if (leadingLabelMatch && leadingLabelMatch.index !== undefined) {
    const before = text.slice(0, leadingLabelMatch.index);
    const tail = text.slice(leadingLabelMatch.index + leadingLabelMatch[0].length);
    // Only strip if the visible tail has substantive answer text.
    if (tail.trim().length >= 1) {
      text = (before + tail).trimStart();
    }
  }
  return text;
}

// If a future failure shows a different refusal phrasing, add a new
// pattern with its own guard test rather than silently expanding the
// detector. Operating rule: each new pattern needs its own false-positive
// guard test that exercises a substantive answer containing the new noun
// or qualifier.
function isProviderRefusal(text: string): boolean {
  if (typeof text !== "string") return false;
  const trimmed = text.trim();
  if (trimmed.length === 0) return false;
  // Test the trimmed text as-is, and again with a single trailing
  // punctuation character stripped, so "I don't have specific details."
  // matches even with the trailing period.
  const candidates = [trimmed, trimmed.replace(/[.,!?]$/, "")];
  const pattern = new RegExp(
    [
      // Patterns 1-4: original first-person anchored patterns. Noun
      // alternation is unified to the same memory-record noun list.
      // Each allows an optional (any |specific |relevant ) qualifier
      // between "have/see/find/recall" and the noun.
      String.raw`\bI (?:do not|don't|did not|didn't) have (?:any |specific |relevant )?(?:details|information|memory|memories|record|records)\b`,
      String.raw`\bI (?:do not|don't|did not|didn't) (?:see|find|recall) (?:any |specific |relevant )?(?:information|details|records?|memories?)\b`,
      String.raw`\bI have no (?:record|information|details) (?:of|about|on|regarding)\b`,
      String.raw`\bI'm not able to (?:recall|find|determine) (?:any |specific |relevant )?(?:information|details|records?)\b`,
      // Pattern 5: no "I" anchor; matches third-person "no X were/are/was/is found/available/on file/recorded/stored" form.
      String.raw`\bno (?:relevant |specific )?(?:details|information|memory|memories|record|records) (?:were |are |was |is )?(?:found|available|on file|recorded|stored)\b`,
      // Pattern 6 (new in this revision): article-gap pattern. The
      // determiners a, an, the, any, specific, relevant are all accepted
      // in a single flat alternation, so the model can phrase the
      // refusal with an article ("a specific summary", "an entry", "the
      // relevant notes") and the detector still matches. The
      // determiner group accepts 0+ stacked determiners in a sequence
      // (e.g. "a specific summary", "the relevant notes") via the `*`
      // quantifier, so multi-determiner refusal phrasings also match.
      // This pattern addresses the live failure phrase "I don't have a
      // specific summary for session 2 in the available memories."
      String.raw`\bI (?:do not|don't|did not|didn't) have (?:a |an |any |the |specific |relevant )*(?:details|information|memory|memories|record|records|summary|summaries|entry|entries|note|notes)\b`,
    ].join("|"),
    "i",
  );
  return candidates.some((c) => pattern.test(c));
}

/**
 * Validate and harden the provider's synthesized answer text.
 *
 * Order of operations (each gate may short-circuit with `AnswerFail`):
 *
 *   1. Empty-answer gate            (skip empty or whitespace-only input)
 *   2. Reasoning-block strip        (remove `think...` etc.)
 *   3. Empty-after-strip gate       (reject if stripping left nothing)
 *   4. Whitespace normalization     (CRLF/tabs -> single space)
 *   5. Secret-redaction step        (`redactSummary` redaction)
 *   6. Empty-after-redaction gate   (reject if redaction ate everything)
 *   7. Short-after-redaction gate   (reject if non-secret content is thin)
 *   8. Memory-id reference strip    (remove `Memory #N`, `entry #N`,
 *                                    bare `#N`, etc., enforcing the
 *                                    no-IDs-in-public-text invariant
 *                                    on the content path)
 *   9. Raw-dump check               (reject structural-looking dumps)
 *  10. Refusal-shape check          (reject provider refusal phrasings)
 *
 * The memory-id strip (step 8) runs after secret-redaction (so
 * redaction is not perturbed) and before the raw-dump and refusal
 * checks (so those detectors see the stripped text). It enforces the
 * no-IDs-in-public-text invariant on the `answered` content path:
 * the synthesis LLM may echo the id-bearing `- #N kind: summary`
 * format it sees in its prompt, and that echo must not reach the
 * public `text` block.
 *
 * Note: there is intentionally NO length cap here. The synthesis
 * prompt and the disciplined model choice control length on the
 * input side; on the output side natural-length answers go to the
 * wire unmodified.
 */
function validateAnswer(answer: string): AnswerOk | AnswerFail {
  if (typeof answer !== "string" || answer.trim().length === 0) {
    return { ok: false, reason: "provider returned an empty answer" };
  }
  // Strip provider reasoning blocks (`<think>...</think>`,
  // `<thinking>...</thinking>`, leading `Reasoning:` / `Thought:`)
  // before validation. This keeps the public output free of the
  // model's internal scratchpad while preserving the visible
  // answer.
  const stripped0 = stripReasoningBlocks(answer).trim();
  if (stripped0.length === 0) {
    return {
      ok: false,
      reason: "provider answer was only reasoning; no visible answer to return",
    };
  }
  // Normalize whitespace. No length cap — see the doc comment above.
  const text = stripped0.replace(/\r\n?/g, "\n").replace(/[ \t]+/g, " ");
  // Defense in depth: redact any secret-shaped fragment that the
  // provider may have echoed.
  const redacted = redactSummary(text);
  const stripped = redacted.replace(/<redacted>/g, "").trim();
  if (stripped.length === 0) {
    return {
      ok: false,
      reason: "provider answer was entirely redacted as secret content",
    };
  }
  if (stripped.length < 10) {
    return {
      ok: false,
      reason:
        "provider answer contained insufficient non-secret content after redaction",
    };
  }
  // Strip memory-id references from the post-redaction text. This
  // pass runs after the secret-redaction step (so redaction is not
  // affected) and after the short-after-redaction check (so the
  // length gate sees the redacted text, not the stripped text). It
  // runs before the raw-dump and refusal checks so those detectors
  // see the stripped text — a refusal that includes a memory-id
  // reference (e.g. "I don't have specific details about memory
  // #37") should have the reference removed before the refusal
  // detector evaluates the text, so the detector works on the
  // underlying intent rather than on a structural echo of the id.
  // The strip pass enforces the no-IDs-in-public-text invariant
  // for the `answered` content path: the synthesis LLM may echo
  // the id-bearing `- #N kind: summary` format it sees in its
  // prompt, and that echo must not reach the public `text` block.
  const noIds = stripMemoryIdReferences(redacted);
  if (looksLikeRawDump(noIds)) {
    return {
      ok: false,
      reason:
        "provider answer looks like a raw dump rather than a synthesized answer",
    };
  }
  // Refusal-shape check runs last: the structural-safety gates
  // above (empty, reasoning-strip, secret-redaction,
  // short-after-redaction, raw-dump) have already cleared, and
  // this gate only fires on text that has passed them. A refusal
  // text that also contains a secret fragment is still caught by
  // the redaction step first; the refusal check then reclassifies
  // a thin-overlap refusal into `no_memory` at the call site.
  if (isProviderRefusal(noIds)) {
    return { ok: false, reason: "refusal_detected" };
  }
  return { ok: true, answer: noIds };
}

function looksLikeRawDump(text: string): boolean {
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length < 3) return false;
  let dumpLines = 0;
  for (const l of lines) {
    if (/^[A-Z][A-Z0-9_]{2,}=.+$/.test(l)) dumpLines += 1;
    if (/^\s*\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}/.test(l)) dumpLines += 1;
  }
  return dumpLines / lines.length > 0.6;
}

// ---------------------------------------------------------------------------
// Phase 3A: recall stage trace emission
// ---------------------------------------------------------------------------
//
// The three helpers below build and emit the Phase 3A stage
// events. They are kept out of the main `runRecallController`
// body so the hot path stays readable, and so the trace payload
// shapes are discoverable in one place. All three are pure
// functions over the existing controller state plus a
// `RecallTraceContext`; they never mutate the controller state
// and never read raw provider I/O.
//
// The writer's `redactPayload` pass scrubs credentials and
// drops reasoning keys from the persisted JSON, so a future
// secret that ends up in a memory body or query text is
// caught at the storage boundary without the controller having
// to know about it. The controller does NOT attempt to redact
// its own payload.

/**
 * Emit `recall.active-memory-read` — the count of active memory
 * summaries read from storage and the `storageLimit` that bounded
 * the read. Pure read-side diagnostic; no memory ids are carried
 * (the lexical-ranking event carries them, ranked, instead).
 *
 * The event fires even when no memories exist (count is 0) so a
 * reader can distinguish "DB has nothing" from "recall never got
 * that far" — important for diagnosing a stale-recall bug where
 * the controller read zero rows.
 */
function emitActiveMemoryReadStage(
  trace: RecallTraceContext | undefined,
  payload: {
    readCount: number;
    storageLimit: number;
  },
): void {
  // Short-circuit on disabled / closed writers or when no trace
  // context was provided. The check is intentionally outside the
  // payload-builder so we never build the payload object when
  // tracing is off.
  if (!trace || trace.runId === null) return;
  trace.recordStage(RECALL_ACTIVE_MEMORY_READ_KIND, {
    readCount: payload.readCount,
    storageLimit: payload.storageLimit,
  });
}

/**
 * Emit `recall.lexical-ranking` — the query, the ranker
 * threshold / topK, and the ranked candidates that passed the
 * threshold (in the same order the ranker returned them, which
 * is score-desc / id-asc).
 *
 * Each candidate carries:
 *   - `id`            : memory id
 *   - `rank`          : 1-based position in the ranked list
 *   - `score`         : raw lexical score from the ranker
 *   - `overlap`       : absolute count of query tokens that
 *                      appeared in the candidate's match text
 *                      (summary + tags). Re-computed via
 *                      `scoreCandidateDetailed` so the trace
 *                      matches the ranker's own per-candidate
 *                      calculation byte-for-byte. The ranker
 *                      uses an `overlap >= MIN_OVERLAP_TOKENS`
 *                      floor; the trace event surfaces the
 *                      post-floor value.
 *   - `memoryContent` : the safe memory body the ranker scored
 *                      (controller-normalized text, never raw
 *                      input). Redacted by the writer before
 *                      persistence.
 *   - `kind`          : memory kind enum
 *   - `tags`          : tag list (possibly empty)
 *   - `classification`: free-form classification string or null
 *   - `confidence`    : provider confidence or null
 *
 * Memory content is included so a reader can verify what the
 * ranker actually saw. For the live user-test failure (memory
 * 151 about a provider swap not being recalled for a general
 * "what LLMs does this project use" query), this event will
 * show whether memory 151 was in the candidate pool, what it
 * scored, and what its content was — the diagnostic the user
 * asked for.
 *
 * When the ranker filters out every candidate, the `ranked`
 * array is empty and the event still fires (so a reader can
 * see the empty result rather than infer "never ranked").
 */
function emitLexicalRankingStage(
  trace: RecallTraceContext | undefined,
  payload: {
    query: string;
    threshold: number;
    topK: number;
    ranked: LexicalScoredCandidate[];
    summariesById: Map<number, SafeMemorySummary>;
  },
): void {
  if (!trace || trace.runId === null) return;
  const rankedDetail = payload.ranked.map((r, index) => {
    const s = payload.summariesById.get(r.id);
    // `summariesById` is the same map the controller uses to
    // build `topSummaries`; a missing entry here would mean the
    // ranker returned an id that isn't in the read set, which
    // is impossible in the current code path. We fall back to
    // an empty match text so the trace event still records
    // (id, score, overlap=0) for the unexpected id rather
    // than crashing the trace.
    const matchText = s ? buildMatchText(s) : "";
    const { overlap } = matchText
      ? scoreCandidateDetailed(payload.query, matchText)
      : { overlap: 0 };
    return {
      id: r.id,
      rank: index + 1,
      score: r.score,
      overlap,
      memoryContent: s ? s.memoryContent : null,
      kind: s ? s.kind : null,
      tags: s ? s.tags : [],
      classification: s ? s.classification : null,
      confidence: s ? s.confidence : null,
    };
  });
  trace.recordStage(RECALL_LEXICAL_RANKING_KIND, {
    query: payload.query,
    threshold: payload.threshold,
    topK: payload.topK,
    ranked: rankedDetail,
  });
}

/**
 * Emit `recall.selected-candidates` — the `topSummaries` the
 * controller is about to feed to the synthesis provider, with
 * the memory id and the controller-normalized memory body. This
 * is the ground-truth "what went into the synthesis call" set;
 * a reader can compare it against `recall.lexical-ranking` to
 * see which ranked candidates were promoted to synthesis and
 * which were dropped.
 *
 * The `topSummaries` already inherit the ranker's score-sorted
 * order, so the position in this array matches the rank. We
 * surface a 1-based `synthesisOrder` for readability.
 */
function emitSelectedCandidatesStage(
  trace: RecallTraceContext | undefined,
  topSummaries: SafeMemorySummaryWithRelationship[],
): void {
  if (!trace || trace.runId === null) return;
  trace.recordStage(RECALL_SELECTED_CANDIDATES_KIND, {
    candidates: topSummaries.map((s, index) => ({
      id: s.id,
      synthesisOrder: index + 1,
      memoryContent: s.memoryContent,
    })),
  });
}

/**
 * Emit `recall.superseded-demotion` — a summary of superseded-memory
 * demotions applied after lexical ranking and before selected-candidates.
 *
 * The event fires after the demotion step (Phase 3b) to give a reader
 * visibility into what the demotion actually changed. The payload
 * summarizes demotions only:
 *   - `id`            : demoted candidate id
 *   - `rawScore`      : score before demotion
 *   - `demotedScore`  : score after demotion
 *   - `reason`        : `"supersedes"` (this candidate supersedes another)
 *                       or `"supersededBy"` (another candidate superseded this)
 *   - `supersedingId` : the id of the superseding candidate (omitted when
 *                       reason is `"supersedes"` because the superseding
 *                       candidate's score is unchanged)
 *
 * When no demotions occurred, a compact `{demotions: 0}` form is emitted
 * so the reader can distinguish "demotion stage never ran" from
 * "no candidates demoted."
 *
 * Raw memory text and secrets are intentionally omitted from the payload.
 * The writer's `redactPayload` pass scrubs credentials from the persisted
 * JSON, so a future secret in a memory body is caught at the storage
 * boundary without the controller having to know about it.
 */
function emitSupersededDemotionStage(
  trace: RecallTraceContext | undefined,
  args: {
    /** Candidates before demotion (the lexical-ranked list). */
    before: ReadonlyArray<{ id: number; score: number }>;
    /** Candidates after demotion (the demoted-ranked list). */
    after: ReadonlyArray<{ id: number; score: number }>;
    /** Relationship blocks for candidates that were demoted. */
    demotedIds: ReadonlySet<number>;
    /** Map from stale id to superseding id (only populated when reason is supersededBy). */
    supersededByMap: ReadonlyMap<number, number>;
  },
): void {
  if (!trace || trace.runId === null) return;

  // Build the demotion summary. We compute it by scanning the after list
  // for candidates whose score changed (demoted) and looking up the
  // corresponding before entry for rawScore.
  const demotions: Array<{
    id: number;
    rawScore: number;
    demotedScore: number;
    reason: "supersedes" | "supersededBy";
    supersedingId?: number;
  }> = [];

  const beforeMap = new Map<number, number>();
  for (const c of args.before) {
    beforeMap.set(c.id, c.score);
  }

  for (const c of args.after) {
    if (!args.demotedIds.has(c.id)) continue;
    const rawScore = beforeMap.get(c.id) ?? c.score;
    // Determine reason: if this id has a superseding id in the map,
    // reason is "supersededBy"; otherwise "supersedes".
    const supersedingId = args.supersededByMap.get(c.id);
    demotions.push({
      id: c.id,
      rawScore,
      demotedScore: c.score,
      reason: supersedingId !== undefined ? "supersededBy" : "supersedes",
      ...(supersedingId !== undefined ? { supersedingId } : {}),
    });
  }

  if (demotions.length === 0) {
    // Compact form: no demotions occurred.
    trace.recordStage(RECALL_SUPERSEDED_DEMOTION_KIND, { demotions: 0 });
  } else {
    trace.recordStage(RECALL_SUPERSEDED_DEMOTION_KIND, { demotions });
  }
}

/**
 * Reconstruct the match text the ranker used for a candidate so
 * the trace event's `overlap` field matches the ranker's own
 * per-candidate value. The ranker builds
 * `summary + (" " + tags.join(" "))` when tags are present; we
 * mirror that exactly so a test asserting `overlap === N` is
 * consistent with the ranker's internal computation.
 */
function buildMatchText(s: SafeMemorySummary): string {
  const tagPart =
    Array.isArray(s.tags) && s.tags.length > 0
      ? ` ${s.tags.join(" ")}`
      : "";
  return `${s.memoryContent}${tagPart}`;
}

// ---------------------------------------------------------------------------
// Clarification helpers
// ---------------------------------------------------------------------------

/**
 * Heuristic: is the query obviously vague or underspecified?
 *
 * Conservative: fires only on short, generic-reference-only
 * queries that are extremely likely to be underspecified.
 * Does NOT fire on queries that are short but contentful
 * (e.g. "API design", "meeting notes").
 *
 * The heuristic:
 *   - 3 or fewer tokens AND
 *   - all tokens are generic reference words (not specific content)
 *
 * Generic reference words: pure deictics (it, this, that, its,
 * their), articles (the, a, an), vague nouns (thing, stuff,
 * something, anything, everything), or question words that are
 * likely refrences (what, which) when the query is very short.
 */
function isVagueQuery(query: string): boolean {
  if (typeof query !== "string") return false;
  const trimmed = query.trim();
  if (trimmed.length === 0) return false;

  // Tokenize: split on whitespace, strip punctuation for the check
  const tokens = trimmed
    .toLowerCase()
    .split(/\s+/)
    .map((t) => t.replace(/^[^\w]+|[^\w]+$/g, "")) // strip leading/trailing non-word chars
    .filter((t) => t.length > 0);

  // Must be 3 or fewer tokens to be considered "short"
  if (tokens.length > 3) return false;

  // Generic reference word set
  const genericWords = new Set([
    "it", "its", "this", "that", "these", "those",
    "the", "a", "an",
    "thing", "things", "stuff", "something", "everything", "nothing",
    "what", "which", "who", "where", "when", "why", "how",
    "there", "here",
    "last", "next", "previous", "earlier", "later",
    "some", "any", "all", "none", "no",
  ]);

  // Every token must be a generic word (no content term)
  return tokens.every((t) => genericWords.has(t));
}

/**
 * Heuristic: does the weak_match coverage suggest competing/conflicting
 * candidates?
 *
 * Conservative: fires when the top score is very low (suggesting
 * weak match quality) OR when there are multiple candidates with
 * similar scores (competing matches).
 *
 * A topScore below 0.1 is a strong signal the query doesn't match
 * anything well. A supportingCount >= 3 with a narrow score gap
 * between top and rest suggests ambiguity about which memory is
 * actually relevant.
 */
function suggestsCompetingCandidates(
  topScore: number,
  supportingCount: number,
): boolean {
  // Very low top score: query doesn't match anything well
  if (topScore < 0.1) return true;

  // Multiple candidates with similar scores (competing interpretations)
  if (supportingCount >= 3 && topScore < 0.3) return true;

  return false;
}
