#!/usr/bin/env node
/**
 * Regenerate `src/version.ts` from `package.json`.
 *
 * The package version is the single source of truth — this script
 * reads `package.json#version` and writes a small generated
 * TypeScript module that exports a `VERSION` constant. The file is
 * intentionally short and dependency-free so it can be required
 * from both the runtime entrypoint (`src/index.ts`) and the
 * server-wiring module (`src/server.ts`).
 *
 * Wired into `prebuild` and `pretest` in `package.json` so the
 * generated file is always in sync before a build or test run.
 *
 * Idempotent: if the existing `src/version.ts` already matches the
 * generated content, the file is left untouched. This keeps
 * incremental builds and re-runs cheap and avoids touching mtime
 * unnecessarily.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const pkgPath = path.join(REPO_ROOT, "package.json");
const outPath = path.join(REPO_ROOT, "src", "version.ts");

const pkgRaw = fs.readFileSync(pkgPath, "utf8");
let pkg;
try {
  pkg = JSON.parse(pkgRaw);
} catch (err) {
  const msg = err instanceof Error ? err.message : String(err);
  // Build-time tool — stderr is fine here; this is not the curion
  // server runtime.
  process.stderr.write(`[curion] sync-version: failed to parse package.json: ${msg}\n`);
  process.exit(1);
}
const version = pkg.version;
if (typeof version !== "string" || version.length === 0) {
  process.stderr.write(
    "[curion] sync-version: package.json is missing a non-empty `version` field\n"
  );
  process.exit(1);
}

const header = [
  "/**",
  " * Generated from package.json. Do not edit by hand.",
  " *",
  " * Regenerated by `scripts/sync-version.mjs`, wired into",
  " * `prebuild` and `pretest` in `package.json`.",
  " * The source of truth is `package.json#version`.",
  " */",
  "",
].join("\n");

// JSON.stringify produces a safely-escaped, quoted string literal
// that TypeScript accepts verbatim.
const body = `export const VERSION = ${JSON.stringify(version)};\n`;
const newContent = header + body;

let existing = null;
try {
  existing = fs.readFileSync(outPath, "utf8");
} catch {
  // file doesn't exist yet — that's fine, we'll create it
}

if (existing !== newContent) {
  fs.writeFileSync(outPath, newContent);
  process.stdout.write(`[curion] sync-version: wrote src/version.ts (${version})\n`);
} else {
  process.stdout.write(`[curion] sync-version: src/version.ts already up to date (${version})\n`);
}