/**
 * `recall(text)` tool.
 *
 * Public MCP contract (unchanged):
 *   - Accepts exactly one public `text` parameter (string).
 *   - Returns a `text` content block carrying a short human-readable
 *     answer, or `No relevant memory found.` when retrieval finds
 *     nothing.
 *   - Must not accept kinds, states, filters, providers, debug, or
 *     storage arguments.
 *
 * MVP behavior:
 *   - `answered`            -> the synthesized answer.
 *   - `no_memory`           -> "No relevant memory found."
 *   - `rejected`            -> a short reason that does not echo
 *                              the query (e.g. obvious secret in
 *                              the query).
 *   - `provider_error`      -> a short, redacted reason; the
 *                              controller does not fabricate an
 *                              answer when the provider fails.
 *
 * Phase D (spec §5.4): when the recall-side ambiguity detector
 * (Phase C) returns a `kind: "ambiguous"` signal on the
 * answered outcome, the public `message` is prefixed with a
 * short, bounded, conservative note generated by
 * `formatAmbiguityNote` in `src/retrieval/ambiguity.ts`. The
 * underlying `answer` text is unchanged; the note is a
 * prefix only. When the detector returns `kind: "none"`, the
 * public `message` is byte-equal to the pre-Phase-D message
 * (the pre-Phase-D message was the synthesized answer; the
 * Phase D code path that emits a prefix is skipped). The
 * `no_memory` / `rejected` / `provider_error` outcomes are
 * unchanged in every case.
 *
 * Phase J (spec §8.4): when the recall-side resolved-history
 * detector (Phase H) returns a `kind: "resolved-history"`
 * signal on the answered outcome, the public `message` is
 * prefixed with a short, bounded, conservative note
 * generated by `formatResolvedHistoryNote` in
 * `src/retrieval/resolved-history.ts`. The note is the exact
 * approved prose string (`Note: I found earlier related
 * information, but newer entries appear to supersede it.`)
 * and carries no `#N` memory-id reference. The underlying
 * `answer` text is unchanged; the note is a prefix only.
 *
 * Composition rule (spec §4.2 / §4.3, mirrored in
 * `formatOutcome`):
 *   1. If the Phase D ambiguity detector fired
 *      (`internalAmbiguity.kind === "ambiguous"`), the
 *      ambiguity note is prefixed. The resolved-history
 *      note is **not** prefixed on the same outcome: a
 *      stored-conflict pointer wins (the Phase D detector
 *      stays silent on resolved-history when the Phase D
 *      warning would fire, by spec §4.2).
 *   2. Else, if the Phase J resolved-history detector fired
 *      (`internalResolvedHistory.kind ===
 *      "resolved-history"`), the resolved-history note is
 *      prefixed.
 *   3. Else, no note is prefixed; the public `message` is
 *      byte-equal to the synthesized answer.
 *
 * The Phase J invariant (added by
 * `experiment/public-message-hide-memory-ids`): the public
 * `message` must not reintroduce `#N` memory-id references
 * into the public text. The `formatResolvedHistoryNote`
 * helper applies the same no-id-in-public-text contract
 * `formatAmbiguityNote` applies. The detector's internal
 * `memoryIds` array remains on `ResolvedHistorySignal`; the
 * structured `sourceIds` field on `RecallResult` remains
 * intact.
 *
 * The `no_memory` / `rejected` / `provider_error` outcomes
 * are unchanged in every case.
 *
 * The public message is the only thing the MCP `text` content
 * block carries. Structured fields are exposed via `outcome` for
 * tests and any future structured-content transport.
 *
 * Storage and provider behavior are not exposed to the caller.
 */

import {
  runRecallController,
  type RecallOutcome,
} from "../controller/recall-controller.js";
import {
  initStorage,
  closeStorage,
  type StorageHandle,
} from "../storage/storage.js";
import { formatAmbiguityNote } from "../retrieval/ambiguity.js";
import { formatResolvedHistoryNote } from "../retrieval/resolved-history.js";
import { logger } from "../logging/logger.js";
import { startToolBoundaryTrace } from "../trace/index.js";
import { z } from "zod";

export const RECALL_TOOL_NAME = "recall" as const;
export const RECALL_TOOL_DESCRIPTION =
  "Retrieve relevant project memory. Returns a synthesized answer from stored memories, or 'No relevant memory found.'.";

export const NO_RELEVANT_MEMORY = "No relevant memory found.";

/**
 * Locked public text for the `weak_match` outcome (refusal-
 * with-thin-match). The synthesis LLM declined to answer but
 * the lexical ranker surfaced relevant stored memories.
 * Byte-equal, no LLM involvement. Surfaced verbatim as the
 * on-the-wire `text` content block for the `weak_match`
 * status; the top-3 summaries and the coverage block ride
 * on `structuredContent`.
 */
export const WEAK_MATCH_PUBLIC_MESSAGE =
  "I found relevant memories but could not synthesize a confident answer; the retrieved notes are listed in structuredContent.";

export interface RecallInput {
  text: string;
}

/**
 * Strict Zod v3 object schema for the public `recall` tool
 * input. `.strict()` makes the MCP SDK's `validateToolInput`
 * reject any unknown top-level key — the only acceptable key
 * is `text`. The SDK wires this through to the on-the-wire
 * `tools/list` JSON schema (with `additionalProperties: false`
 * via the strict-Union projection), so the public input
 * contract is pinned at the schema level, not just at the
 * handler level.
 *
 * Schema surface (preserved):
 *   - one `text` property (string, required, min 1)
 *   - no kinds, states, filters, providers, debug, or storage
 *     knobs
 */
export const RECALL_INPUT_SCHEMA = z
  .object({
    text: z
      .string()
      .min(1, "text must not be empty")
      .describe("The query to recall memory for."),
  })
  .strict();

/**
 * Tool-layer result. The `message` field is the only field the MCP
 * `text` content block carries. Structured fields are exposed via
 * `outcome` for tests and any future structured-content transport.
 *
 * The public message is never allowed to echo raw input, raw
 * queries, or secret-shaped fragments. The controller returns
 * `provider_error` (not a fabricated answer) when the synthesis
 * output fails validation.
 *
 * Phase D + Phase J: when `status === "answered"` and the
 * recall-side detector(s) fire, the `message` field is the
 * formatted note (ambiguity OR resolved-history, per the
 * composition rule in the module header) followed by the
 * synthesized answer on a new line. The `answer` field is
 * always the unmodified synthesized answer text. When neither
 * detector fires (the MVP default), `message` and `answer` are
 * both the synthesized answer text (byte-equal to pre-Phase-D
 * and pre-Phase-J).
 */
export interface RecallResult {
  status: RecallOutcome["status"];
  /** Short human-readable message. Never echoes raw input. */
  message: string;
  /** Synthesized answer, when `status === "answered"`. */
  answer?: string;
  /** Memory ids the answer was synthesized from, when answered. */
  sourceIds?: number[];
  /**
   * Internal-only note(s) the recall-side detectors fired
   * on the answered outcome, populated for the wire-format
   * projection. Each entry is the prose note as returned by
   * `formatAmbiguityNote` / `formatResolvedHistoryNote`
   * (the `Note: ` prefix is preserved in this field; the
   * wire-projection layer strips it). Empty or absent when
   * no detector fires. The composition rule (spec §4.2 /
   * §4.3) allows at most one entry; the field is named
   * `notes` (plural) to keep the surface stable if a future
   * composition rule ever emits more than one.
   *
   * Not part of the user-facing surface. Tests and the
   * wire-format projection in
   * `src/tools/recall-projection.ts` read this field; the
   * on-the-wire MCP `text` content block and
   * `structuredContent` are the only public-facing outputs.
   */
  notes?: string[];
  /**
   * Refusal-with-thin-match: top-3 curator-voice summaries
   * the ranker surfaced before the synthesis LLM refused
   * to answer. Populated when `status === "weak_match"`.
   * Plain strings; no memory-id reference (the no-IDs
   * rule is enforced at the schema level — the
   * structuredContent entry is a `string[]`, not a list
   * of objects with id fields). Capped at 3 entries by
   * the controller.
   */
  summaries?: string[];
  /**
   * Refusal-with-thin-match: coverage metadata. Populated
   * when `status === "weak_match"`. `topScore` is the raw
   * lexical score of the top-ranked candidate (a ranker-
   * confidence proxy); `supportingCount` is the count of
   * candidates that passed the ranker threshold, NOT
   * capped by the top-K=3 slice.
   */
  coverage?: { topScore: number; supportingCount: number };
  /** Safety class, when `status === "rejected"`. */
  safetyClass?: string;
}

export interface StorageProviderHandle {
  handle: StorageHandle;
  /** True if the tool should call `closeStorage` after the call. */
  ownsHandle: boolean;
}

type StorageProvider = () => StorageProviderHandle;
let storageProvider: StorageProvider = () => {
  const handle = initStorage();
  return { handle, ownsHandle: true };
};

/** Test/extension hook. Production code does not call this. */
export function setStorageProvider(provider: StorageProvider): void {
  storageProvider = provider;
}

/** Test/extension hook. Resets to the default (per-call) provider. */
export function resetStorageProvider(): void {
  storageProvider = () => {
    const handle = initStorage();
    return { handle, ownsHandle: true };
  };
}

/**
 * Run the narrow `recall(text)` pipeline. Defensive shape check
 * on `input.text`, then delegate to the controller.
 *
 * Tool-boundary tracing (Phase 2): every public invocation
 * opens a single trace run and records one `tool.input` event at
 * entry, one `tool.output` event with the result the handler
 * returns, and the run's final status + duration on exit. The
 * tracer is the existing non-throwing writer; trace failures
 * NEVER change the result and NEVER throw into the MCP path.
 */
export async function handleRecall(input: unknown): Promise<RecallResult> {
  // Open the trace run at the public tool boundary. The helper
  // is a no-op when `CURION_TRACE_ENABLED=0` or the writer is
  // unavailable; in either case the rest of the handler runs
  // unchanged.
  const trace = startToolBoundaryTrace({ toolName: "recall", input });
  try {
    if (
      typeof input !== "object" ||
      input === null ||
      typeof (input as { text?: unknown }).text !== "string"
    ) {
      // Validation failure (programmer / SDK error — the strict
      // schema should already have rejected this). The trace run
      // finishes as `error` and re-throws.
      throw new Error("recall: `text` (string) is required");
    }
    const text = (input as { text: string }).text;
    if (text.trim().length === 0) {
      throw new Error("recall: `text` (string) must be non-empty");
    }

    const { handle: storage, ownsHandle } = storageProvider();
    let outcome: RecallOutcome;
    try {
      outcome = await runRecallController(storage, text);
    } catch (err) {
      // Unexpected throw — log and surface a provider_error outcome.
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`recall: unexpected controller error: ${msg}`);
      const result: RecallResult = {
        status: "provider_error",
        message:
          "recall: unexpected internal error; no memory was returned",
      };
      // The handler returned a result, so the run is `ok` (the
      // handler itself did not throw). The provider_error status
      // is captured in the persisted tool.output event.
      trace.recordOutput(result);
      trace.finish("ok");
      return result;
    } finally {
      if (ownsHandle) {
        try {
          closeStorage(storage);
        } catch {
          // ignore
        }
      }
    }

    const result = formatOutcome(outcome);
    trace.recordOutput(result);
    trace.finish("ok");
    return result;
  } catch (err) {
    // The handler itself threw (validation or some other
    // unexpected path). Record the run as `error` and re-throw
    // so the MCP layer sees the original error.
    trace.finish("error");
    throw err;
  }
}

function formatOutcome(outcome: RecallOutcome): RecallResult {
  switch (outcome.status) {
    case "answered": {
      // Composition rule (spec §4.2 / §4.3):
      //   1. If the Phase D ambiguity detector fired
      //      (`internalAmbiguity.kind === "ambiguous"`),
      //      the ambiguity note is prefixed. The
      //      resolved-history note is NOT prefixed on the
      //      same outcome (a stored conflict pointer wins;
      //      see spec §4.2).
      //   2. Else, if the Phase J resolved-history
      //      detector fired
      //      (`internalResolvedHistory.kind ===
      //      "resolved-history"`), the resolved-history
      //      note is prefixed.
      //   3. Else, no note is prefixed; the public
      //      `message` is byte-equal to the synthesized
      //      answer.
      //
      // Both note formatters are pure helpers from the
      // retrieval modules; both are bounded and produce
      // prose only (no `#N` memory-id references, no
      // `Sources: #...`, no "and N more" truncation). The
      // `answer` field is always the unmodified synthesized
      // answer; the note is a prefix on the *message*
      // only. When no detector fires, the public
      // `message` and `answer` are both the synthesized
      // answer text (byte-equal to pre-Phase-D and
      // pre-Phase-J).
      const ambiguityNote = formatAmbiguityNote(outcome.internalAmbiguity);
      const resolvedHistoryNote = formatResolvedHistoryNote(
        outcome.internalResolvedHistory,
      );
      const note =
        ambiguityNote.length > 0
          ? ambiguityNote
          : resolvedHistoryNote;
      const message =
        note.length === 0
          ? outcome.answer
          : `${note}\n\n${outcome.answer}`;
      return {
        status: "answered",
        message,
        answer: outcome.answer,
        sourceIds: [...outcome.sourceIds],
        // Internal-only `notes` (plural, may be empty). The
        // note is the prose returned by the recall-side
        // detector formatters; the `Note: ` prefix is
        // preserved here and stripped at the wire-projection
        // boundary (see `src/tools/recall-projection.ts`).
        notes: note.length > 0 ? [note] : [],
      };
    }
    case "no_memory":
      return {
        status: "no_memory",
        message: NO_RELEVANT_MEMORY,
      };
    case "weak_match":
      // Refusal-with-thin-match: the synthesis LLM declined
      // to answer but the lexical ranker did surface
      // relevant stored memories. The public `message` is
      // the locked public text (byte-equal, no LLM
      // involvement); the top-3 summaries and the coverage
      // block ride on the wire-format projection as
      // `structuredContent` (see `buildRecallStructuredContent`).
      // No memory ids are exposed — the `summaries` are
      // plain strings, the `coverage` block has no id
      // fields, and the public text carries no `#N`
      // reference.
      return {
        status: "weak_match",
        message: WEAK_MATCH_PUBLIC_MESSAGE,
        summaries: [...outcome.summaries],
        coverage: { ...outcome.coverage },
      };
    case "rejected":
      return {
        status: "rejected",
        message: `Rejected: ${outcome.reason}`,
        safetyClass: outcome.safetyClass,
      };
    case "provider_error":
      return {
        status: "provider_error",
        message: `Provider error: ${outcome.reason}`,
      };
  }
}
